/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tk: {
          green: "#00a884",
          "green-dark": "#008069",
          accent: "#25d366",
          teal: "#008069",
          out: "#d9fdd3",
          "out-dark": "#005c4b",
          in: "#ffffff",
          "in-dark": "#202c33",
          bg: "#eae6df",
          "bg-dark": "#0b141a",
          panel: "#ffffff",
          "panel-dark": "#111b21",
          header: "#f0f2f5",
          "header-dark": "#202c33",
          ink: "#111b21",
          "ink-dark": "#e9edef",
          muted: "#54656f",
          "muted-dark": "#aebac1",
          line: "#e9edef",
          "line-dark": "#2a3942",
          search: "#f0f2f5",
          "search-dark": "#202c33",
          shell: "#d1d7db",
          "shell-dark": "#0a1014",
        },
      },
      fontFamily: {
        sans: [
          "Segoe UI",
          "Nirmala UI",
          "Kalinga",
          "Noto Sans Oriya",
          "Noto Sans Devanagari",
          "Noto Sans",
          "Roboto",
          "Helvetica Neue",
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
      },
      boxShadow: {
        bubble: "0 1px 0.5px rgba(11, 20, 26, 0.13)",
      },
    },
  },
  plugins: [],
};
